from den.settings.base import get_env_variable


SLACK_WEBHOOK_BASE_URL = get_env_variable('SLACK_WEBHOOK_BASE_URL')
SLACK_WEBHOOK_CHANNEL_ID = get_env_variable('SLACK_WEBHOOK_CHANNEL_ID')
SLACK_WEBHOOK_CHANNEL_URL = '{0}{1}'.format(SLACK_WEBHOOK_BASE_URL, SLACK_WEBHOOK_CHANNEL_ID)