# Generated by Django 2.0.6 on 2018-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiselevel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
