# Generated by Django 2.0.6 on 2018-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20180610_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expertiselevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knowledgestore',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
