# Generated by Django 2.0.6 on 2019-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='resources',
            field=models.ManyToManyField(related_name='packet', to='knowledge.KnowledgeStore'),
        ),
    ]
