# Generated by Django 2.0.6 on 2019-08-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hustlers', '0001_initial'),
        ('knowledge', '0007_auto_20190804_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='sequence_no',
        ),
        migrations.AddField(
            model_name='knowledgestore',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_store_updated', to='hustlers.Hustler'),
        ),
    ]
