# Generated by Django 2.0.6 on 2018-06-24 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0003_auto_20180610_0728"),
        ("auth", "0009_alter_user_last_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hustler",
            fields=[
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "django_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="hustler",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hustlers.Hustler",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True, related_name="hustlers", to="knowledge.Category"
                    ),
                ),
            ],
            options={"db_table": "hustlers",},
        ),
    ]
