# Generated by Django 2.0.6 on 2019-08-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hustlers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hustler",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hustlers_modified",
                to="hustlers.Hustler",
            ),
        ),
        migrations.AlterField(
            model_name="hustler",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hustlers.Hustler",
            ),
        ),
    ]
